
services:
  - type: web
    name: fastapi-app
    runtime: python
    region: oregon
    plan: free
    repo: https://github.com/Dan-Gaya/HNG12-STGE2-BOOKAPI.git
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh
    envVars:
      - key: PORT
        value: 10000
