name: Deploy to Koyeb

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Koyeb
        run: |
          curl -X POST -H "Authorization: Bearer ${{ secrets.KOYEB_API_KEY }}" \
          -d '{"service_name": "fastapi-app"}' \
          https://api.koyeb.com/v1/deploy
