name: CI Pipeline

on:
  pull_request:
    branches:
      - main  # Triggers only on pull requests to the main branch

jobs:
  test:
    name: Run Pytest
    runs-on: ubuntu-latest  # Use latest Ubuntu runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Fetch code from repo

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"  # Match your local Python version

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies

      - name: Run tests
        run: |
          source venv/bin/activate
          pytest -v  # Run pytest
